Internal Server Error: /api/v1/suppliers/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 29, in get_queryset
    return self.queryset.filter(id__in=[dto.id for dto in suppliers_dto])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
"GET /api/v1/suppliers/?q=3&page=1&page_size=25 HTTP/1.1" 500 105478
